title: Gané kraft
description: Nova wikipédia
theme: just-the-docs

url: ganecraft.github.io
favicon_ico: "favicon.ico"
color_scheme: dark

aux_links:
  Fontos: https://youtu.be/VffzX1rJHtM&t=26s
  Ingyen pénz: https://youtu.be/dQw4w9WgXcQ
  Youtube: https://www.youtube.com/channel/UCIYV0HSKkGdbRtjSnS9JiSQ

aux_links_new_tab: true