title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: ganecraft.github.io
favicon_ico: "/assets/img/favicon.ico"
color_scheme: dark

aux_links:
  Nekladek: https://nekladek.github.io
  Youtube: https://www.youtube.com/channel/UCIYV0HSKkGdbRtjSnS9JiSQ

aux_links_new_tab: true